//
// Created by student on 23.12.2019.
//

#include "ThingException.h"

ThingException::ThingException(std::string n)
: logic_error(n)
{
}
